name: Build PHAR and upload to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.2'
      PHAR_TARGET_BASENAME: liveptoto.phar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, gmp
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set VERSION (strip leading v if present)
        id: set_version
        run: |
          TAG='${{ github.event.release.tag_name }}'
          VERSION="${TAG#v}"
          VERSION="${VERSION#V}"
          echo "Tag from event: $TAG"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build PHAR into v/<version>/liveptoto.phar
        env:
          VERSION: ${{ env.VERSION }}
          PHAR_NAME: ${{ env.PHAR_TARGET_BASENAME }}
        run: |
          set -euo pipefail
          if [ -z "${VERSION:-}" ]; then
            echo "VERSION is empty — cannot continue"
            exit 1
          fi

          OUT_DIR="v/$VERSION"
          OUT_PATH="$OUT_DIR/$PHAR_NAME"

          mkdir -p "$OUT_DIR"
          echo "Building PHAR at $OUT_PATH"

          # Remove old phar if exists
          rm -f "$OUT_PATH"

          # Use php's Phar to pack src/, vendor/ and common root files
          php -d phar.readonly=0 - <<'PHP'
          $out = getenv('OUT_PATH') ?: null;
          if (!$out) {
              // read from env passed via heredoc as fallback
              $out = "${OUT_DIR}/${PHAR_NAME}";
          }
          // But the above won't work inside this heredoc; so we use getenv properly
          $out = getenv('OUT_PATH');
          if (!$out) {
              fwrite(STDERR, "OUT_PATH env var missing\n");
              exit(1);
          }

          // Clean any existing file
          if (file_exists($out)) unlink($out);

          $phar = new Phar($out, 0, basename($out));
          $phar->startBuffering();

          // directories to add (adjust if you want different content)
          $dirs = ['src', 'vendor'];
          foreach ($dirs as $d) {
              if (is_dir($d)) {
                  $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($d, RecursiveDirectoryIterator::SKIP_DOTS));
                  foreach ($it as $file) {
                      /** @var SplFileInfo $file */
                      $filePath = $file->getRealPath();
                      $local = ltrim(str_replace(getcwd(), '', $filePath), '/');
                      $phar->addFile($filePath, $local);
                  }
              }
          }

          // add a few root files if present
          foreach (['composer.json','README.md','LICENSE'] as $f) {
              if (file_exists($f)) {
                  $phar->addFile($f, $f);
              }
          }

          // create a simple stub so the PHAR can be required/used
          $stub = <<<'STUB'
#!/usr/bin/env php
<?php
Phar::mapPhar();
if (file_exists('phar://' . __FILE__ . '/vendor/autoload.php')) {
    require 'phar://' . __FILE__ . '/vendor/autoload.php';
}
__HALT_COMPILER();
STUB;
          $phar->setStub($stub);
          $phar->stopBuffering();
          echo "PHAR created at $out\n";
          PHP
        env:
          OUT_PATH: ${{ github.workspace }}/v/${{ env.VERSION }}/${{ env.PHAR_TARGET_BASENAME }}

      - name: Verify PHAR exists
        run: |
          ls -l "v/${{ env.VERSION }}/$PHAR_TARGET_BASENAME"
          file "v/${{ env.VERSION }}/$PHAR_TARGET_BASENAME" || true

      - name: Upload PHAR to the Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: v/${{ env.VERSION }}/${{ env.PHAR_TARGET_BASENAME }}
          asset_name: v/${{ env.VERSION }}/${{ env.PHAR_TARGET_BASENAME }}
          asset_content_type: application/octet-stream
